server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YasiruWickramanayake/test-configuration-files
          search-paths:
           - '*service'



